### ISSUE TITLE
Discord SRV & Xclaim

### ISSUE THREAD

**Issue by RainbowTea** [WasabiThumb/xclaim#10]
When you add a name for trusting it will send the name to the text channel for Discord SRV. I'm not sure if this is intended but wondering if we can some how prevent this?

**Comment by WasabiThumb** [comment]
There are two methods that DiscordSRV uses for listening to chat events ([new](https://github.com/DiscordSRV/DiscordSRV/blob/018b179dcd65f1833169a406af3c35d042d0b809/src/main/java/github/scarsz/discordsrv/listeners/ModernPlayerChatListener.java#L56) and [old](https://github.com/DiscordSRV/DiscordSRV/blob/018b179dcd65f1833169a406af3c35d042d0b809/src/main/java/github/scarsz/discordsrv/listeners/PlayerChatListener.java#L36)) which both use EventPriority.MONITOR. This is meant for "monitoring the outcome of an event" according to Bukkit docs and the event will be run regardless of whether or not it has been previously cancelled by another plugin. If they want to only display messages that are visible in chat (commands actually don't count, they use their own system) then they should be *checking* to see if the event has previously been cancelled or at least add this check as an option in the config. Hence this is a shortcoming on the part of DiscordSRV and you should make an issue there instead. I could add a special exception in XClaim but I would rather not add the bloat when the source of the issue is external.

**Comment by Vankka** [comment]
`RespectChatPlugins` defaults to `true` and is not included in the config by default. 

Issue is fixed by setting `UseModernPaperChatEvent` to `true` in the DiscordSRV config because the paper event runs after the old bukkit event since Paper 1.18

**Comment by WasabiThumb** [comment]
When 1.8.0 releases, XClaim will no longer use the Paper event for cancelling chat events anyways, which will obsolete this fix. Very weird that it does that anyways, thanks for the knowledge bomb @Vankka
