### ISSUE TITLE
Add 1.21 support

### ISSUE THREAD

**Issue by Kittycraft0** [WasabiThumb/xclaim#105]
Hello, I am combining my xclaim server with geysermc, among other things, which i think requires the latest minecraft version. i noticed this plugin still sort of works in 1.21, albeit lacking a few features. Could 1.21 support be added soon?

Lacked features that I've noticed:
- clicking on arrows in help menu in the chat does not work, clicking on yes in the chat to "would you like to update" does not work
- Walking in a claim/walking out of a claim does not anymore give the indicator saying "entering/leaving iwbmo's Tower" or similar

Thanks

**Comment by WasabiThumb** [comment]
It sounds like you are using an outdated version of the plugin, the 2nd issue at the very least is likely caused by an outdated version of Adventure. Adventure handles chat stuff, and 1.21 introduced some big changes there. Plugin version [1.13.1](https://github.com/WasabiThumb/xclaim/releases/tag/1.13.1) includes the latest version of Adventure. Please make sure you are using the latest version of the plugin, and in general, make sure you are using the latest version before creating an issue.
