### ISSUE TITLE
Event support to API

### ISSUE THREAD

**Issue by Khontrom** [WasabiThumb/xclaim#108]
Add Events Support (example ClaimCreateEvent, ClaimDeleteEvent etc.) to API

**Comment by WasabiThumb** [comment]
Added experimental API events to the [feat/events](https://github.com/WasabiThumb/xclaim/tree/feat/events) branch. If no issues are found, it will be included in release **1.14**.

Events (feel free to suggest more):
- _XClaimModifyClaimEvent_
  - **XClaimCreateClaimEvent** : After a claim is initialized, but before it is canonized
  - **XClaimDeleteClaimEvent** : Before a claim is deleted
  - _XClaimModifyClaimChunksEvent_
    - **XClaimAddChunksToClaimEvent** : Before chunk(s) are added to a claim
      - **XClaimAddChunkToClaimEvent** : Before a chunk is added to a claim
    - **XClaimRemoveChunksFromClaimEvent** : Before chunk(s) are removed from a claim
      - **XClaimRemoveChunkFromClaimEvent** : Before a chunk is removed from a claim

The reason why ``AddChunk``/``RemoveChunk`` are subclasses of ``AddChunks``/``RemoveChunks`` is because while it is not currently possible to claim multiple chunks at once, this may change (#111)

**Comment by Khontrom** [comment]
Thanks for your interest. It would be great if some more events could be added. For example, ClaimUserAdd, ClaimUserRemove, ClaimOwnerTransfer events can be added.

**Comment by WasabiThumb** [comment]
Added a few more events; previous message updated.

**Comment by WasabiThumb** [comment]
Staged for [1.14](https://github.com/WasabiThumb/xclaim/pull/121)
