### ISSUE TITLE
Enhancement Idea: Extra Category for Rockets

### ISSUE THREAD

**Issue by eingruenesbeb** [WasabiThumb/xclaim#11]
Hey, I'm using this plugin on a server I manage and the players there have an idea for enhancement (actually two, but one step at a time...):
So the problem is, that using rockets is in the same category as interactions (like pressing buttons). As such players are not able to use them, if this category is disabled for them. So the proposed solution is to put them in a separate category, because using rockets is essential for movement.

**Comment by WasabiThumb** [comment]
Sure, what I will probably do is add an exception for using rockets while flying with elytra, since using a rocket in general can cause damage and other undesirable effects. There is already an exception like this for reading books and (somewhat) for eating food. I don't see why these should be in a separate category since they are integral to gameplay.

**Comment by eingruenesbeb** [comment]
One tricky thing might be fireworks, that do damage, as those could be used to kill entities within the chunk. So maybe only add fireworks, with only flight duration and nothing else, if possible?
Otherwise adding an exception like you described would be good 👍🏻

**Comment by WasabiThumb** [comment]
I've already added handlers for damage due to projectiles by checking the owner of the projectile. I believe that fireworks are considered projectiles by the game? I will test this when I implement it

**Comment by WasabiThumb** [comment]
Fixed in the latest commit, will be included in the 1.8.0 release.

**Comment by eingruenesbeb** [comment]
Thanks 😄
