### ISSUE TITLE
Enhancement idea: A way to disable explosions in claimed Chunks

### ISSUE THREAD

**Issue by eingruenesbeb** [WasabiThumb/xclaim#12]
Hey, so here's another idea/issue players had:

The problem is, that people could still grief claimed chunks with creepers or TNT. A possible solution would be the ability to disable explosions in a claim.

Oh, and as a side note:
I've made a german translation I could make a pull request for, if you want.

**Comment by WasabiThumb** [comment]
Here is the complicated thing about disabling explosions. The permission system in this plugin is based on trust levels, (all players, trusted players, veterans, none). So for blocking an event we inherently need to know who caused it, to see if they belong in the permission group. It is sometimes very clear who caused TNT to go off (directly lit by a flint & steel) and sometimes basically impossible or would cause a lot of overhead to find out, something I don't really want for this plugin. Then I guess what we would do is this:
**If the TNT source is unclear**:
- If the permission level is anything other than ALL then don't let it blow up

**If the TNT source is clear**:
- If the permission level is anything other than NONE and it is a creeper, then let it blow up
- Follow normal permission rules for players

Does that sound good to you?

--

If you would like to add a PR for your translation that would be great, just add your de.json [here](https://github.com/WasabiThumb/xclaim/tree/master/src/main/resources/lang), AND optimally a partially or fully translated [README.md](https://github.com/WasabiThumb/xclaim/blob/master/README.md) (eg. README.de.md) that I can link at the top of the main README.md. If partially translated, please leave something like "more details in the English version", etc at the bottom. Thanks for your contribution! <3

**Comment by eingruenesbeb** [comment]
The suggestion you make about how this could be implemented sounds good, except for the creeper... The problem would be, if a player is intentionally and maliciously leading a creeper into claimed chunks and letting it blow up, that this player could circumvent the whole no explosions thing. Or am I misinterpreting this? Is there a way to check who the creeper is targeting, without introducing much overhead?

**Comment by WasabiThumb** [comment]
> The suggestion you make about how this could be implemented sounds good, except for the creeper... The problem would be, if a player is intentionally and maliciously leading a creeper into claimed chunks and letting it blow up, that this player could circumvent the whole no explosions thing. Or am I misinterpreting this? Is there a way to check who the creeper is targeting, without introducing much overhead?

My perspective is this: creepers exploding is an expected part of vanilla gameplay, and since this plugin is meant for use in SMPs it should only be blocked if the owner of the claim is absolutely affirmative about having no explosions. In general, this plugin views mobs as fully privileged, for example endermen can still pick up blocks. It would be strange to break the trend here. If you want to have absolute control over what can happen in an area, then use WorldGuard. The plugins will not interfere with each other, you can have both active at the same time.

I admit that purposeful griefing using creepers is a bit troublesome although hard to pull off effectively... It definitely shouldn't be possible to do. And I also bet that the average player would think the TRUSTED or VETERAN groups for explosions should block creepers from exploding, but that would go against the design philosophy.... I'm trying to think of a decent compromise. It would probably be fairly easy to find out who caused an explosion to happen, maybe if the person who caused the explosion is not privileged, we have the creeper still cause damage but not grief any blocks? Please let me know.

**Comment by WasabiThumb** [comment]
This has been added to 1.8.0 as described above, you can download it [here](https://github.com/WasabiThumb/xclaim/releases/download/1.8.0/xclaim-1.8.0.jar) or auto-update ingame with ``/xc update``. Also be sure to translate the new keys if you are PRing that German translation :)
```json
 "perm-explode-name": "Explosions",
 "perm-explode-description": "Cause explosions; when the source of an explosion is unclear, TRUSTED and VETERAN groups act like NONE",
  ```
If you find any issues with this implementation be sure to open a new issue. Thanks!

**Comment by eingruenesbeb** [comment]
Oh, you just closed it, as I was writing this. 😅 Anyways, I'll still post my answer to your question from before.
The way I would expect it to be implemented it is essentially, what you described in the last paragraph. Still letting the creeper cause damage, but not letting it cause block damage, if the one, who caused the creeper to explode is not in the privileged group. 
Well, in any case, I'll take a look at the new version and thanks for the quick response and even implementation of this idea.

P.S.: Regarding the German translation, I'll make sure to include the new 1.8.0 translation keys and I'll probably have it ready today (At least my today... Time-zones and such, you know...).

**Comment by WasabiThumb** [comment]
Of course, thanks! Sorry for being so trigger-happy on the close button, I like to tie up loose ends before I forget. I have bad memory :)
