### ISSUE TITLE
When you start a fire from outside of the claim (even if it's closed in settings) fire spreads to the claim

### ISSUE THREAD

**Issue by Krayir5** [WasabiThumb/xclaim#124]
A player in my server made a build and then some player griefed it. He thinked that closing that setting will stop the fire but no fire spread to the base too and while you're close to the build you can do explosions and claim gets damage too. Can you fix it?

**Comment by WasabiThumb** [comment]
That's not really enforcable, essentially we would have to flag fire blocks when created explicitly and then transfer that data whenever the fire spreads. Same with TNT, we would have to flag the entity and transfer the data. This could cause an _exponential data explosion_, which I don't really want to be party to.

Failing that, there's always going to be some sufficiently complicated trigger mechanism (for example; dropper drops an item onto a pressure plate, which powers a piston that pushes a redstone block into a dispenser that dispenses a TNT) that would etiher make it infeasible to track the original source or hang the server trying to figure it out. That's why no claim system tries, and just has an on & off setting for TNT. If you set the TNT permission to None, this will do that. But it still can't do anything about TNT on the edge of your claim.

I've always advocated for claiming 1 extra chunk on the perimeter of your claim for situations like this. :)
