### ISSUE TITLE
Barrier item can be obtained

### ISSUE THREAD

**Issue by RHX0R3** [WasabiThumb/xclaim#157]
Hello,

similar to the issue #154, players can still illegally get a barrier.

Through the Allay mob:
![393624397-a6ed2b23-1c26-4f1a-9fe6-18538a3ee103](https://github.com/user-attachments/assets/d85ea09d-bd14-4241-bdf9-5d7a46d6a2cc)

Through the Armor Stand entity (with arms):
![393626327-fc96e388-8fbf-419b-8391-173b2c6754f6](https://github.com/user-attachments/assets/c94f120f-5822-4a62-95cb-bef69dbe070b)

Please fix asap! ❤️

**Comment by tt-thoma** [comment]
That's a huge amount of events lmao 😵‍💫
Isn't there a generic paper event that could just handle right clicking on anything/anywhere?
Or perhaps using interaction hitboxes around the player's head

**Comment by WasabiThumb** [comment]
> That's a huge amount of events lmao 😵‍💫
> Isn't there a generic paper event that could just handle right clicking on anything/anywhere?

Theoretically that would be PlayerInteractEvent, which is currently handled.

However:
- Mojang has little reason to care about how they change the protocol from version to version
- Bukkit/Spigot/Paper events are triggered by specific *code paths*, and their names/descriptions are attempts to explain what that code path means for us. PlayerInteractEvent is an obvious name for the code path of "we got this packet that's sent when the client clicks something", but it is by no means a promise that the event will be called any time the client presses a mouse button. If Mojang decides that a certain interaction has no reason to send that packet, like changing the inventory of an armor stand, then it sneakily slips out of this event.

> Or perhaps using interaction hitboxes around the player's head

This is a decent idea, though I fear it would obscure otherwise solveable issues like these, and it would be defeated by server lag or a hacked client. So it can't be the only solution. It would also be massively version-dependent, which is infeasible for a 1.8+ project maintained by 1 person. It would be included in v2 (1.18+) if anything.

**Comment by WasabiThumb** [comment]
Sorry about the delay, I've had a lot going on (was in hospital for 3 days). Should be able to tackle this soon

**Comment by WasabiThumb** [comment]
The fix might actually be quite simple. ``PlayerInteractEntityEvent`` does not extend ``PlayerInteractEvent`` (because of course), so handling interactions does not necessarily handle entity interactions. I [went ahead and fixed that](https://github.com/WasabiThumb/xclaim/compare/master...bug/entity-item-leak). It's worth noting that ``PlayerItemFrameChangeEvent`` does not extend ``PlayerInteractEntityEvent``, so this update doesn't obsolete the new protections for item frames. Those were always an exception to the interaction system. :/

Dev Build (debug mode enabled): [xclaim-1.15.2.jar](https://file.io/9UgitpCNY8jo)

**Comment by RHX0R3** [comment]
Hello, the dev build slows down the server incredibly hard.
An awful amount of "Can't keep up..." messages. But no errors or stacktraces.

But I could confirm, that the Allay mob is fixed. The armorstand still did take the barrier. Although I don't know, if that was the result of the slow-down or not.

I switched back to 1.15.1.

**Comment by WasabiThumb** [comment]
> Hello, the dev build slows down the server incredibly hard.
> An awful amount of "Can't keep up..." messages. But no errors or stacktraces.
> 
> But I could confirm, that the Allay mob is fixed. The armorstand still did take the barrier. Although I don't know, if that was the result of the slow-down or not.
> 
> I switched back to 1.15.1.

Would you be willing to take a Spark profile to determine the lag source? Simply need to add Spark to the server and use the start/stop command. Optimally at least a few seconds of analysis and when lag is high (especially when you don't expect it to be).

Also is this a report for 1.15.2 (release) or 1.15.2 (dev)? I noticed you said you switched to 1.15.1 (release).

**Comment by RHX0R3** [comment]
Nevermind, ProtocolLib shat itself...

**Comment by RHX0R3** [comment]
Can you provide the link again? I deleted the dev build :o

**Comment by WasabiThumb** [comment]
Going to add an explicit check for [PlayerArmorStandManipulateEvent](https://jd.papermc.io/paper/1.21.4/org/bukkit/event/player/PlayerArmorStandManipulateEvent.html), which is unfortunate since it subclasses ``PlayerInteractEvent`` and should already be handled. Will update.

**Comment by WasabiThumb** [comment]
Ok, [did that](https://github.com/WasabiThumb/xclaim/commit/3e1a2a7af2eb253518638b37f6da0be90fad8fdc).

Here's a build with the new change: [xclaim-1.15.2.jar](https://file.io/8z0htE4Iev4g)

**Comment by WasabiThumb** [comment]
I have no idea why the recording is flashing, but it looks fine for me.

https://github.com/user-attachments/assets/4c55423f-1847-4b0b-b9bd-f818cfa2a1f8
