### ISSUE TITLE
[Critical] Explosion-Protection not sufficient

### ISSUE THREAD

**Issue by TheFoxCraft** [WasabiThumb/xclaim#158]
The Explotion-Protection works well when the Origin (eg. TNT) is inside the claimed chunkt, but if the TNT is one block out of the Claimend Region it also damages the blocks inside the claimed region, where it shouldn´t.
I am using Paper 1.21.4 (Snapshot) and Plugin-Version 1.15.2

**Comment by WasabiThumb** [comment]
As mentioned before (#124, #33) this is not likely to be fixed. It would incur *exponential costs* on explosions, and provides a route to hang/crash the server. To whatever extent this is a design flaw, it is alleviated entirely by having a 1+ extra chunk perimeter on the edge of claims, which has been the historical reccomendation.

This issue is "addressed" in v2 (WIP), but it would be irresponsible of me to promise perfection.

**Comment by WasabiThumb** [comment]
First "working" build of v2 is here

https://github.com/user-attachments/assets/722b3acb-9211-4fba-bc46-edeac27c2dce
