### ISSUE TITLE
Enhancement: select worlds for the plugin to work in

### ISSUE THREAD

**Issue by H7KZ** [WasabiThumb/xclaim#19]
Make config var that contains worlds and then check if the plugin is allowed to run in that world.
Also good to make whitelist/blacklist so another variable that would change the bool of the array of worlds ^

**Comment by WasabiThumb** [comment]
Question about implementation: do you believe this should just prevent players from creating/managing claims in a blacklisted world, or should it also not enforce permissions on claims that exist in a blacklisted world? If a claim is made in a world and the world is later blacklisted, what should happen? Does the claim get deleted in some sort of routine? Do we or do we not enforce the permissions set on the claim?

I think that having claims work the same no matter what is the more elegant solution, and that blacklisting should just make it so that you cant create/manage claims in a world, but I'm not sure what most people would want

**Comment by H7KZ** [comment]
Good point. There could be a function to check if the world contains any claims and then inform the user about it. So like the user would have a 7day period to clear/delete his claim in the blacklisted world. But It would not allow to create a new one afterwards. and when the 7day period ends (could be checked every hour or so) then the claim gets deleted and the items in it are open to public.

I dont know how difficult would be to code this although it is the most reasonable answer to this kind of problem.

**Comment by WasabiThumb** [comment]
That could definitely work. Definitely a bit more involved than other solutions but I agree its fairly elegant. And if the period is configurable, setting it to 0 or less would delete claims immediately. Since there isn't any way to change the config and therefore whether or not a world is blacklisted without restarting the plugin (at the moment) the startup event can be used to check if there are any claims in a blacklisted world and therefore if the routine should start.

Guess I'll start then 😜 it could never be as tedious as supporting those ancient versions of minecraft

**Comment by H7KZ** [comment]
Wait. Why couldn't you also put the checking into /xclaim reload?

**Comment by WasabiThumb** [comment]
> Wait. Why couldn't you also put the checking into /xclaim reload?

Well effectively I am. XClaim reloads the plugin, so onEnable is called shortly afterwards

**Comment by WasabiThumb** [comment]
Sorry have my hands a little full as of late my goal is to close this by tonight but no promises. A temporary solution would be one of those "per world plugin" plugins out there however it probably wont stop XClaim from enforcing existing claims in blacklisted worlds just stop people from using the chunk editor or making new claims in them

**Comment by H7KZ** [comment]
Oh. Well. I don't need it that soon. Sort your things first

**Comment by WasabiThumb** [comment]
I've made two commits on the development branch that should do the trick but needs to be tested

**Comment by WasabiThumb** [comment]
Fixed a problem with timing and added the new config keys to README, we are good to go now

**Comment by WasabiThumb** [comment]
Included in 1.9.3
