### ISSUE TITLE
add request 

### ISSUE THREAD

**Issue by florosss** [WasabiThumb/xclaim#2]
Hello already thank you for your plugin I find it a pity that there is no translation file would it be possible to see to add in the next updates & integrate the economy to make the chunk pay that would be really good 

 sorry for my bad english i am french

**Comment by WasabiThumb** [comment]
Language files are about half way implemented at this point (228 lines of text!) likely will be done within 24 hours

**Comment by WasabiThumb** [comment]
Language support is done
https://github.com/WasabiThumb/xclaim#languages

Must use version >= 1.6.x

**Comment by florosss** [comment]
thank you for this update and this speed I will work on the French translation and I will give you the file if you want to make it available and do you think you can work on the integration of an economic system similar to ClaimChunk 
economy:
 useEconomy: true
  claimPrice: 500.0
  unclaimReward: 0
  firstFreeChunks: 1
  
  I'm waiting for this to replace ClaimChunk with your plugin thank you very much and sorry for my very bad english

**Comment by WasabiThumb** [comment]
That's basically what I was going to do in terms of economy support, just a bit busy right now.

If you want, you can also translate the [README.md](https://raw.githubusercontent.com/WasabiThumb/xclaim/master/README.md)
I have basic conversational ability with french but I'm not good enough to translate this well

**Comment by WasabiThumb** [comment]
Basic economy support has been drafted but requires testing
Here are the details of the implementation:

use-economy has been added to the config with a default value of false

claim-price, unclaim-reward, and free-chunks are now [group properties](https://github.com/WasabiThumb/xclaim#config) like max-chunks and max-claims. This makes it so that admins can set different prices for different groups, etc. For example if you wanted to set the default claim price to 5.75, you would change ``limits.default.claim-price`` in the config to 20. The name "limits" no longer makes sense so it may be changed to "groups" over the course of a few versions as to not break existing setups.

The following keys have been added to the en-US lang:
```json
{
  "chunk-editor-cant-afford": "<red>* You need <gold>$1</gold> in order to purchase this chunk!</red>",
  "chunk-editor-pay-fail": "<red>* Failed to deduct <gold>$1</gold> from your account.</red>",
  "chunk-editor-reward": "<green>* Rewarded <gold>$1</gold> for unclaiming this chunk</green>",
  "eco-fail": "No suitable economy plugin was found"
}
```

To reiterate, these changes won't go into effect or appear on GitHub until proper testing is done.

**Comment by WasabiThumb** [comment]
Economy support has been fully implemented in 1.7.0. Read the README for more information and/or download [here](https://github.com/WasabiThumb/xclaim/releases/latest).

**Comment by florosss** [comment]
thank you very much for working on the features I requested,Very good pl, i would like to donate do you have a page for that

**Comment by WasabiThumb** [comment]
> thank you very much for working on the features I requested,Very good pl, i would like to donate do you have a page for that

I actually don't have a donation link right now, that's a good idea to have. And very generous of you! I will maybe make one soon.

I also saw the issue you posted on Spigot resources and I think it's related to your translation, try seeing if you get the same error with en-US because I can't reproduce it. Also whenever you are done with your translation I would be happy to add it as an option in the plugin
