### ISSUE TITLE
Adding players to claims 

### ISSUE THREAD

**Issue by dshikhman** [WasabiThumb/xclaim#27]
Not sure if this is an issue or if I am doing something wrong. Every time I try to add a player to my claim to edit their permissions, I tab their name in chat, and I am told that "Couldn't find a player with that name.".

**Comment by WasabiThumb** [comment]
> Not sure if this is an issue or if I am doing something wrong. Every time I try to add a player to my claim to edit their permissions, I tab their name in chat, and I am told that "Couldn't find a player with that name.".

Are you using their real username or their nickname? Are they online or offline? What version of the plugin are you using?

**Comment by dshikhman** [comment]
> 
Real username, online, version 1.19 on a 1.19 server.

**Comment by WasabiThumb** [comment]
Not sure why it isnt working then, maybe send a video?

**Comment by dshikhman** [comment]
sure, here is the video https://drive.google.com/file/d/1_eWTOYEyw6MAQkYUl4QFZajc26mL_wIc/view?usp=sharing

and these are the real names of players

**Comment by WasabiThumb** [comment]
This is very weird, what software is the server running on? Spigot? Paper? Something else? Any kind of proxy running like Bungee or Waterfall or something?

**Comment by dshikhman** [comment]
Spigot, no proxy, online, no firewall, server is hosted from Bisect Hosting from NY (USA).

**Comment by WasabiThumb** [comment]
I'm really not sure how this is possible, assuming you are using plugin version 1.9.0 (you said 1.19 im guessing you meant 1.9), [this method](https://github.com/WasabiThumb/xclaim/blob/1.9.0/src/main/java/codes/wasabi/xclaim/util/NameToPlayer.java#L24) would have to return null which is only possible if [this call](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Bukkit.html#getPlayer(java.lang.String)) returns null, which will _only ever happen_ (according to Bukkit docs) if there is no player online with that username. I could make an update that provides nickname support but I dont think it would solve your problem because you've made it very clear you are using real usernames. Is that player connected through Geyser or something?

**Comment by WasabiThumb** [comment]
@dshikhman Please check out 1.9.5, I think it may have solved your problem.

**Comment by WasabiThumb** [comment]
Did this fix your issue? Will close if no response
