### ISSUE TITLE
Adjacent Claim Chunks

### ISSUE THREAD

**Issue by RainbowTea** [WasabiThumb/xclaim#37]
I am on paper 81,1.19

I claimed an island, just the edge all around it to link it up in order to use the adjacent claim chunk feature. It  showed its all claimed on the map. However, in-game if i walk round it'll say I'm leaving the claim or entering it often. So that tells me the chunks inside the island aren't claimed.

I go in and edit my claim chunks. Use the green dye to claim chunks. I go around and i can see that the inside claim chunks say 'open' and I am able to claim it.

I'm not sure if this is a bug or something, but it is concerning.

**Comment by WasabiThumb** [comment]
That's not what the feature does. You must explicitly claim all chunks that you want to be claimed, you cannot claim just the perimeter and expect it to be filled automatically.

The feature, if I understand what you're talking about, toggles whether all chunks in a claim must be next to each other or not, and whether or not they can be diagonal or only directly across on the chunk grid.

It's just a restriction for users on what chunks can be claimed together, it's not some kind of fill bucket feature. For large claims I can understand this would take a while but it IS intentional.

**Comment by RainbowTea** [comment]
I see.  I suppose I was confused because the dynmap is making it appear as if it is a bucket fill feature. I understand what you are showing in the MS paint drawing, but it does not look like either of those. What is happening is a filled in square is shown on the map. I hope you can understand my confusion on here prior to our conversation.

**Comment by WasabiThumb** [comment]
> I see. I suppose I was confused because the dynmap is making it appear as if it is a bucket fill feature and everyone on my server assumed as such too when we saw a filled in square pop up.. I understand what you are showing in the MS paint drawing, but it does not look like either of those. What is happening is a filled in square is shown on the map. I hope you can understand my confusion on here prior to our conversation.

Yes, your situation is represented by the image on the left.
