### ISSUE TITLE
Some issues and suggestions

### ISSUE THREAD

**Issue by RaulMihai1** [WasabiThumb/xclaim#43]
Hey, I really want to use this plugin for my semi vanilla server and have a couple concerns, the a few issues I have stumbled upon whilst testing the plugin are: 

1. You can use piston to move blocks into a claim (as long as you do it from outside that claim) and grief the claim that way
2. TNT causes damage to the claim if the TNT is ignited and explodes on the border of the claim
3. Respawn Anchors cause damage to the claim and a lot more than the TNT this can cause real bad issues for players
4. Explosions of any kind can cause items such as item frames and dragon eggs to break in the claim regardless if the setting is turned on/off, so if someone has explosions off in their claim and someone spawned a wither in and dragged it to the area it could easily grief it

Now for the suggestions: 

1. Make it so after X amount of playtime all ranks get X amount of claims
2. Disable some of the claim settings from the config altogether, for instance I want to disable the 'Enter' feature altgoether because on an SMP like server it can be very OP and trapping can be really bad especially with no KeepINV off. 
3. Ability to remove all veteran rank features, I get that this is a cool feature to have for most servers but for some instances it feels useless haha, so if there was an option to disable that that would be nice. 

Looking forward to hearing from you and hopefully seeing an update to fix the above issues, if you need any videos or pictures of the above issues I can get them on video for you as well :D

**Comment by WasabiThumb** [comment]
I will consider adding some of these, however note that the "veteran" feature is *not* a rank. It's not going to override or interfere with your current groups setup (I'll assume LuckPerms), it will just magically start allowing players to use permissions set to VETERAN after they have played for the configured amount of time. This is tracked using the vanilla playerdata. However if you just want the feature to remove setting VETERAN on a permission in the GUI since you find it perhaps confusing, that's a fine addition. And note that ranks with the admin override permission/OPs will always be able to do anything.

Now, I will also explain how you can achieve addition #1 with the existing "limits" config. This is also not a rank, it uses the vanilla permission system which rank systems like LuckPerms are required to be compatible with. If you want ALL players (no matter what rank they are in) to have an increased maximum claim count exactly as you described above, simply add a new group:

```
limits:
  some-name-here:
    max-claims: 9999 # max claims here
    give-after: 12345 # time here
```

This will automatically give the player the permission named ``xclaim.group.some-name-here`` after they have played for 12345 seconds. If a player has that permission from the start, they will have 9999 maximum claims.

If you want a role to have 9999 maximum claims right from the start, just give that group the permission. E.g: ``/lp group groupname permission set xclaim.group.some-name-here true``.

In the case where a player is in multiple XClaim groups, they will use the "best" option from any individual group.

Maybe this is a somewhat confusing system, but I find it elegant given that all rank/group systems are somewhat arbitrary and depends wildly on whatever plugin you are using to do it; however each must play nicely with the vanilla permissions system as long as they are made well.

If you have any questions on how to get a certain configuration, just ask :)

**Comment by WasabiThumb** [comment]
Feel free to re-open if you have more questions on this subject.
