### ISSUE TITLE
Missing Claims in Bluemap

### ISSUE THREAD

**Issue by Mvb1122** [WasabiThumb/xclaim#64]
# Summary
When viewing claims from XClaim in BlueMap, claims are missing. On my server, many players have their own claims, but only one claim shows up, so the rest are missing. I'm new to BlueMap, so I may have misconfigured something, but I figure that I should put a report in here. I haven't found any workarounds and no related errors are showing up. 

# Versions
Server Version : Paper 1.20.4
Plugins:
- **BlueMap 3.20**
- **XClaim 1.10.5**
- CoreProtect 23.3
- Floodgate 2.22-Snapshot
- Geyser 2.20-Snapshot
- Multiverse Core 4.3.12
- Multiverse Inventories 4.2.6
- Multiverse Nether Portals 4.2.3
- Multiverse Portals 4.2.3
- ViaBackwards 4.9.1
- ViaRewind 3.0.5
- ViaVersion 4.9.2
- WorldBorder 2.1.5

**Comment by Mvb1122** [comment]
Fixed by https://github.com/Mvb1122/xclaim/commit/08726806000c7f99fba9a73c1c87ea03b8a683f4 on my branch, but my fix is _really_ bad. I think the real fix will rely on waiting longer after BlueMap finishes booting, since all I do in my bodge fix is to delay a tiny bit.

**Comment by Mvb1122** [comment]
Or, well, I'm pretty sure it's an issue with my setup. I'm still using my branch to make better BlueMap support, though.

**Comment by WasabiThumb** [comment]
It really is not an ideal solution, but I'm glad it works for you. XClaim as it currently is, is essentially abandonware. It was originally designed for 1 small server and I was not prepared for it to blow up (seems like I'm not the only one that hates most claim plugins), so each addition that was requested made the codebase less and less usable in a way that could have been avoided if the plugin was initially designed for the general public. I have been intending for a long time to completely remake the plugin with the current GitHub issues & all of the existing features in mind, the best way possible (and maybe with a premium version to make the time worth it). It's not the top of my priorities at the moment since it's not very rewarding and the current plugin seems to work fine enough for enough people but this issue has made me slightly more motivated. I'll probably come out with something in a few months ;)

**Comment by Mvb1122** [comment]
Thanks for your response! I'm looking forward to any progress you make.

**Comment by WasabiThumb** [comment]
I talked to someone from the BlueMap team, and it seems like they are confused as well. But I have a few ideas to try, both to hopefully fix the issue for you in XClaim as well as avoid it in a successor.

**Comment by TBlueF** [comment]
@Mvb1122 Make sure you updated your webapp (delete `./bluemap/web/index.html` and reload bluemap).

If that doesn't fix it then talk to us on the bluemap-discord or open an issue @ BlueMap, if possible with a link to your map that i can look at and see whats wrong :)
