### ISSUE TITLE
Permisions for groups don´t work.

### ISSUE THREAD

**Issue by M3dvidek** [WasabiThumb/xclaim#87]
I have an issue with the permissions.
I used command xclaim.group.admin
and the config file looks like this:
   admin:
    max-chunks: 1000
    max-claims: 100
    free-chunks: -1
    claim-price: 0
Thanks everyone for help.

**Comment by WasabiThumb** [comment]
``xclaim.group.admin`` is not a command. You need to add this permission to the admin group in your permission plugin of choice, for example ``/lp group admin permission set xclaim.group.admin`` if using LuckPerms and you have a group named ``admin``. You can also do ``/lp user Username permission set xclaim.group.admin`` for a per-user basis. Otherwise your config looks good, just make sure that you reload XClaim and that your indentation is consistent. Surround YML in code blocks when posting to GitHub.
